In [14]:
import numpy as np
import os
import random
import cv2

In [5]:
image=np.load(r'E:\FF++\out_real_npy\001_1.npy')

In [6]:
num_channels = image.shape[-1]
correlation_matrix = np.zeros((num_channels, num_channels))

for i in range(num_channels):
    for j in range(num_channels):
        if i != j:
            correlation = np.corrcoef(image[:, :, i].ravel(), image[:, :, j].ravel())[0, 1]
            correlation_matrix[i, j] = correlation

print("Pairwise Channel Correlation Matrix:")
print(correlation_matrix)

Pairwise Channel Correlation Matrix:
[[0.         0.99347701 0.96789252 0.98965525 0.96789252]
 [0.99347701 0.         0.98588568 0.99873802 0.98588568]
 [0.96789252 0.98588568 0.         0.992856   1.        ]
 [0.98965525 0.99873802 0.992856   0.         0.992856  ]
 [0.96789252 0.98588568 1.         0.992856   0.        ]]


In [29]:
sample_size = 50

fake_images = os.listdir('out_fake_npy')
sampled_fake_images = random.sample(fake_images, sample_size)

real_images = os.listdir('out_real_npy')
sampled_real_images = random.sample(real_images, sample_size)

sample_images=sampled_fake_images+sampled_real_images

In [30]:
len(sample_images)

100

In [43]:
correlation_matrices = np.zeros((100, 5, 5))
c=0
for i in sample_images:
    if(c<50):
        path='E:/FF++/out_real_npy/'+str(i)
    else:
        path='E:/FF++/out_fake_npy/'+str(i)
    img=np.load(path)
    for j in range(num_channels):
        for k in range(num_channels):
            if j != k:
                correlation = np.corrcoef(img[:, :, j].ravel(), img[:, :, k].ravel())[0, 1]
                correlation_matrices[c, j, k] = correlation
    c+=1
print(correlation_matrices)

[[[0.         0.99432959 0.99250713 0.99721139 0.99250713]
  [0.99432959 0.         0.98753813 0.99795534 0.98753813]
  [0.99250713 0.98753813 0.         0.99543747 1.        ]
  [0.99721139 0.99795534 0.99543747 0.         0.99543747]
  [0.99250713 0.98753813 1.         0.99543747 0.        ]]

 [[0.         0.9493974  0.81103588 0.92401805 0.81103588]
  [0.9493974  0.         0.93062966 0.99233502 0.93062966]
  [0.81103588 0.93062966 0.         0.96778025 1.        ]
  [0.92401805 0.99233502 0.96778025 0.         0.96778025]
  [0.81103588 0.93062966 1.         0.96778025 0.        ]]

 [[0.         0.99452381 0.95961294 0.99042647 0.95961294]
  [0.99452381 0.         0.9695241  0.99636551 0.9695241 ]
  [0.95961294 0.9695241  0.         0.98663572 1.        ]
  [0.99042647 0.99636551 0.98663572 0.         0.98663572]
  [0.95961294 0.9695241  1.         0.98663572 0.        ]]

 ...

 [[0.         0.98348888 0.94864892 0.97950071 0.94864892]
  [0.98348888 0.         0.97847101 0.997552

In [44]:
average_correlation = np.mean(correlation_matrices, axis=0)
average_correlation

array([[0.        , 0.96179138, 0.91050248, 0.95994653, 0.91846267],
       [0.96179138, 0.        , 0.96007182, 0.99566872, 0.96165902],
       [0.91050248, 0.96007182, 0.        , 0.9804025 , 0.99686781],
       [0.95994653, 0.99566872, 0.9804025 , 0.        , 0.98108765],
       [0.91846267, 0.96165902, 0.99686781, 0.98108765, 0.        ]])

In [45]:
channels_to_remove = np.unravel_index(np.argmax(average_correlation), average_correlation.shape)
channels_to_remove

(2, 4)

In [56]:
import numpy as np

# Your correlation matrix
correlation_matrix = average_correlation

# Find the channel with the highest correlation for each channel
most_correlated_channels={}
for i in range(correlation_matrix.shape[0]):
    max_corr = -1
    max_corr_channel = -1
    for j in range(correlation_matrix.shape[1]):
        if i != j and correlation_matrix[i, j] > max_corr:
            max_corr = correlation_matrix[i, j]
            max_corr_channel = j
    most_correlated_channels[i]=(max_corr_channel,max_corr)

most_correlated_channels = dict(sorted(most_correlated_channels.items(), key=lambda item: item[1][1],reverse=True))

print("Channel - Most Correlated Channel")
for i, (channel,correlation) in most_correlated_channels.items():
    print(f"Channel {i+1} - Channel {channel+1} - Correlation Value: {correlation:.4f}")

Channel - Most Correlated Channel
Channel 3 - Channel 5 - Correlation Value: 0.9969
Channel 5 - Channel 3 - Correlation Value: 0.9969
Channel 2 - Channel 4 - Correlation Value: 0.9957
Channel 4 - Channel 2 - Correlation Value: 0.9957
Channel 1 - Channel 2 - Correlation Value: 0.9618
